# Generated by Django 3.0.8 on 2020-07-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='completed',
            field=models.NullBooleanField(default=False),
        ),
    ]
